AllCops:
  # Accepting all new cops is less work than enabling them one-by-one.
  NewCops: enable
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'

Layout/LineLength:
  Enabled: 100

Style/Documentation:
  Enabled: false
